import Head from "next/head";
import styles from "../../styles/Home.module.css";

function index({ children, title }) {
  return (
    <div className={styles.container}>
      <Head>
        <title> Names of website - {title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </div>
  );
}

export default index;
